### PR TITLE
Lostpass

### PR DESCRIPTION
**Pull request by dclement8**

### CODE REVIEW

**Comment by Super-Baleine** [comment]
Do you wanna some help to solve the conflicts ?

**Comment by dclement8** [comment]
Yes please XD

**Comment by Super-Baleine** [comment]
Okay, wait, i'll see what can i do XD

**Comment by Super-Baleine** [comment]
The problem is the translations files. Do you merged my modifications ?

here : https://github.com/quantacloud/core/commit/7323d3419cab89519958561d095a78338ac67680

capture du 2016-07-18 11 23 32

**Comment by dclement8** [comment]
Hm... I don't know

**Comment by Super-Baleine** [comment]
BIM ! I'M THE BEST ! XDD

**Comment by dclement8** [comment]
Thanks XD

**Comment by Super-Baleine** [comment]
Before coding, think to pull/sync x)

**Comment by Super-Baleine** [comment]
We delete the 'lostpass' branch ?

**Comment by dclement8** [comment]
Yes you can

**Comment by Super-Baleine** [comment]
yeswecanposter-300x200

**Pull request merged**
