### PR TITLE
Closed #133

### LINKED ISSUE #133: Double-click on a file --> download it

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Super-Baleine** [comment]
@Ne0blast please revert your changes with the favorites stuff. We didn't enable it for nothing. Thanks!

**Comment by Super-Baleine** [comment]
also, favorites stuff isn't related to the #133 issue, you need to open a new PR to do another change.

**Comment by ghost** [comment]
Sorry, i didn't wanted to push "favorite" feature ^^

**Comment by Super-Baleine** [comment]
Doesn't matter, never mind :)

**Pull request closed without merging**
